package simulacion.ventanas;

import java.awt.Color;
import java.text.DecimalFormat;
import java.util.Map;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.XYPlot;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;

public class Ventana5_12 extends javax.swing.JFrame {

    public Ventana5_12(Map<Integer, Float> fila1_tamaños, Map<Integer, Float> fila2_tamaños, Double t_promedio, int N_HORAS) {
        super("Clientes restantes en fila 1 y 2 despues de " + N_HORAS + "h");
        XYSeriesCollection datos = new XYSeriesCollection();
        XYSeries fila1 = new XYSeries("Fila 1");
        for (Integer n_clientes : fila1_tamaños.keySet()) {
            fila1.add(n_clientes, fila1_tamaños.get(n_clientes));
        }
        datos.addSeries(fila1);
        XYSeries fila2 = new XYSeries("Fila 2");
        for (Integer n_clientes : fila2_tamaños.keySet()) {
            fila2.add(n_clientes, fila2_tamaños.get(n_clientes));
        }
        datos.addSeries(fila2);
        JFreeChart grafica = ChartFactory.createScatterPlot(
                "Clientes restantes en fila 1 y 2\nTiempo promedio en sistema " + new DecimalFormat("#.##").format(t_promedio) + " min",
                "# Clientes restantes", "# De veces", datos);
        XYPlot plot = (XYPlot) grafica.getPlot();
        plot.setBackgroundPaint(new Color(255, 228, 196));
        ChartPanel panel = new ChartPanel(grafica);
        setContentPane(panel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
